version: '3.8'
services:
  db:
    image: postgres:16
    container_name: litterbox_postgres_db
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    volumes:
      - ./docker-data/.pg-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: litterbox-rabbitmq-server
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ AMQP protocol
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./.docker-data/.rabbitmq-data:/var/lib/rabbitmq

  data_source_simulator:
    build:
      context: ./backend
      dockerfile: src/data_source_simulator/Dockerfile
    container_name: litterbox_data_source_simulator
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    ports:
      - "8001:8001"
    volumes:
      - ./backend/src/data_source_simulator:/app/data_source_simulator
    command: ["python", "litterbox_edge_device_simulator.py"]



